Repository greenbone/gvm-libs, pull requests merged in 2021-04, with the labels that each got.

#472 Use double for scores in vtseverity_t and helpers
  CHANGELOG.md
  base/nvti.c
  base/nvti.h
Labels: backport-to-master

#479 Unify GLib log domains
  CHANGELOG.md
  base/array.c
  base/credentials.c
  base/cvss.c
  base/drop_privileges.c
  base/hosts.c
  base/logging.c
  base/networking.c
  base/nvti.c
  base/pidfile.c
  base/prefs.c
  base/proctitle.c
  base/pwpolicy.c
  base/settings.c
  base/strings.c
  base/version.c
  boreas/alivedetection.c
  boreas/arp.c
  boreas/boreas_error.c
  boreas/boreas_io.c
  boreas/cli.c
  boreas/ping.c
  boreas/sniffer.c
  boreas/util.c
  gmp/gmp.c
  osp/osp.c
  util/authutils.c
  util/compressutils.c
  util/fileutils.c
  util/gpgmeutils.c
  util/kb.c
  util/ldaputils.c
  util/nvticache.c
  util/radiusutils.c
  util/serverutils.c
  util/sshutils.c
  util/uuidutils.c
  util/xmlutils.c
Labels: backport-to-master

#482 Validate for max_scan_hosts scanner preference.
  CHANGELOG.md
  boreas/alivedetection.c
Labels: backport-to-21.04, backport-to-master

#484 Introducing passwordbasedauthentication based on lcrypt and sha512
  .gitignore
  CHANGELOG.md
  CMakeLists.txt
  base/cvss_tests.c
  util/CMakeLists.txt
  util/passwordbasedauthentication.c
  util/passwordbasedauthentication.h
  util/passwordbasedauthentication_tests.c
Labels: backport-to-20.08, backport-to-21.04
