Repository greenbone/gvm-libs, pull requests merged in 2021-05, with the labels that each got.

#489 Update CODEOWNERS
  .github/CODEOWNERS
Labels: backport-to-20.08, backport-to-21.04

#490 Add function to find and return a host from a host list.
  CHANGELOG.md
  base/hosts.c
  base/hosts.h
Labels: backport-to-master

#496 When hash or password are NULL return INVALID rather then ERR
  CHANGELOG.md
  util/passwordbasedauthentication.c
  util/passwordbasedauthentication_tests.c
Labels: backport-to-21.04, backport-to-master

#499 Dont free the kb_path twice.
  CHANGELOG.md
  util/kb.c
Labels: backport-to-master

#508 Add all modules to CI format check
  .circleci/config.yml
  util/gpgmeutils.c
  util/ldaputils.c
  util/passwordbasedauthentication.c
  util/passwordbasedauthentication.h
  util/passwordbasedauthentication_tests.c
  util/xmlutils.c
Labels: backport-to-21.04, backport-to-master
